spring:
  profiles:
    include:
      - domain
      - infra

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    open-in-view: false

logging:
  config: classpath:logback-${spring.config.activate.on-profile}.xml
