spring:
  config:
    activate:
      on-profile: local
  redis:
    host: ${LOCAL_REDIS_HOST}
    port: ${REDIS_PORT}

---

spring:
  config:
    activate:
      on-profile: dev
  redis:
    host: ${DEV_REDIS_HOST}
    port: ${REDIS_PORT}